#!MANAGED-CONFIG http://127.0.0.1:25500/sub?config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Frefs%2Fheads%2Fmaster%2FClash%2Fconfig%2FACL4SSR_AdblockPlus.ini&emoji=true&fdn=true&list=false&target=surge&tfo=false&udp=true&url=%2Fhome%2Frunner%2Fwork%2FVpnClashFaCollector%2FVpnClashFaCollector%2Fsub%2FMARAMBASHI%2Fmixed_base64.txt&ver=4 interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
♻️ 自动选择 = direct

[Proxy Group]
🚀 节点选择 = select,♻️ 自动选择,DIRECT
🌍 国外媒体 = select,🚀 节点选择,♻️ 自动选择,🎯 全球直连
📲 电报信息 = select,🚀 节点选择,🎯 全球直连
Ⓜ️ 微软服务 = select,🎯 全球直连,🚀 节点选择
🍎 苹果服务 = select,🚀 节点选择,🎯 全球直连
🎯 全球直连 = select,DIRECT,🚀 节点选择,♻️ 自动选择
🛑 全球拦截 = select,REJECT,DIRECT
🍃 应用净化 = select,REJECT,DIRECT
🆎 AdBlock = select,REJECT,DIRECT
🐟 漏网之鱼 = select,🚀 节点选择,🎯 全球直连,♻️ 自动选择

[Rule]
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9Mb2NhbEFyZWFOZXR3b3JrLmxpc3Q,🎯 全球直连,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9CYW5BRC5saXN0,🛑 全球拦截,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9CYW5Qcm9ncmFtQUQubGlzdA,🍃 应用净化,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9CYW5FYXN5TGlzdC5saXN0,🆎 AdBlock,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9CYW5FYXN5TGlzdENoaW5hLmxpc3Q,🆎 AdBlock,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9CYW5FYXN5UHJpdmFjeS5saXN0,🆎 AdBlock,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9Hb29nbGVDTi5saXN0,🎯 全球直连,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9SdWxlc2V0L1N0ZWFtQ04ubGlzdA,🎯 全球直连,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9NaWNyb3NvZnQubGlzdA,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9BcHBsZS5saXN0,🍎 苹果服务,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9Qcm94eU1lZGlhLmxpc3Q,🌍 国外媒体,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9UZWxlZ3JhbS5saXN0,📲 电报信息,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9Qcm94eUxpdGUubGlzdA,🚀 节点选择,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9DaGluYURvbWFpbi5saXN0,🎯 全球直连,update-interval=86400
RULE-SET,http://127.0.0.1:25500/getruleset?type=1&url=cnVsZXMvQUNMNFNTUi9DbGFzaC9DaGluYUNvbXBhbnlJcC5saXN0,🎯 全球直连,update-interval=86400
GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼

