scraping:
  lookback_days: 0.5  # بازه زمانی بررسی پیام‌ها (به روز)
  max_pages: 20     # حداکثر تعداد صفحات برای اسکرپ کردن در هر کانال

storage:
  base_path: "src/telegram" # محل ذخیره فایل‌های Markdown استخراج شده
